Remaster console output, and modified some directives

diff --git a/hostmgr b/hostmgr
--- a/hostmgr
+++ b/hostmgr
@@ -21,15 +21,17 @@ fi
 
 function _help()
 {
-    echo -e "Usage: $0 {add|remove} [-h|--help]\n"
+    echo -e "Usage: $0 {add|remove|suspend|resume} [-h|--help]\n"
     echo "  add:            Add a virtual server, and create an user"
-    echo "  remove:         Remove an existing virtual server from apache."
+    echo "  remove:         Remove an existing virtual server."
+    echo "  suspend:        Suspend an existing virtual server."
+    echo "  resume:         Resume an existing virtual server."
     exit 1
 }
 
 function _helpAdd()
 {
-    echo -e "Usage: $0 add -s|--server <name> -u|--user <name> [options]\n"
+    echo -e "Usage: $0 add -s|--server <servername> -u|--user <username> [options]\n"
     echo "Options:"
     echo "  --ssl:          If specified, a Let's Encrypt certificate will be"
     echo "                  generated and will be applied to the virtual server"
@@ -43,14 +45,22 @@ function _helpRemove()
     exit 1
 }
 
+function _helpSuspend()
+{
+    echo -e "Usage: $0 suspend -s|--server <name>\n"
+    exit 1
+}
+function _helpResume()
+{
+    echo -e "Usage: $0 resume -s|--server <name>\n"
+    exit 1
+}
+
 function _createHost()
 {
     # If server is not configured, launch creation
-    echo -n "Checking if vhost is existing... "
     if [ ! -f /etc/apache2/sites-available/$serverName.conf ]
     then
-        echo -e "No\n"
-        
         if [ ! -f $userDir/.wwwUser ]
         then
             # Check for userBasePath dir
@@ -67,12 +77,13 @@ function _createHost()
             # Adding a lock file in user dir to protect other users from removing
             echo "Locking dir for '$userName'..."
             touch $userDir/.wwwUser
-            
+
             echo "Disabling access to '$userDir/.wwwUser' to user '$userName'"
             chmod 066 $userDir/.wwwUser
         fi
-        
+
         # Making dirs
+        echo "Making dirs.."
         echo "   + $serverDir"
         mkdir $serverDir
         echo "   + $serverDir/www"
@@ -80,6 +91,11 @@ function _createHost()
         echo "   + $serverDir/log"
         mkdir $serverDir/log
         
+        # Creating default served file
+        echo "   + Copying default page to the user ~/www/ dir"
+        cp index.php $serverDir/www/index.php
+
+
         # Pregenerating certificate if needed
         if [ $sslSecured == 1 ]
         then
@@ -101,7 +117,7 @@ function _createHost()
   ServerAlias $serverAlias
 
   ErrorLog $serverDir/log/error.log" > /etc/apache2/sites-available/$serverName.conf
-        
+
         if [ $sslSecured == 1 ]
         then
             echo -e "\n  <IfModule mod_rewrite.c>
@@ -119,7 +135,7 @@ function _createHost()
     ServerAlias $serverAlias
 
     ErrorLog $serverDir/log/error.log" >> /etc/apache2/sites-available/$serverName.conf
-        
+
             if [ $chrootHost == 1 ]
             then
                 echo -e "\n    ProxyPassMatch \"^/(.*\.php(/.*)?)$\" \"unix:/run/php/php-fpm.$serverName.sock|fcgi://localhost/www" >> /etc/apache2/sites-available/$serverName.conf
@@ -147,7 +163,7 @@ function _createHost()
             fi
             echo "</VirtualHost>" >> /etc/apache2/sites-available/$serverName.conf
         fi
-        
+
         # Configuring CGI
         echo "Creating php-fpm pool for '$serverName'..."
         echo "[$serverName]
@@ -168,7 +184,7 @@ chdir = /www/" >> $serverDir/pool.cfg
             echo -e "\n; Default pool settings
 chdir = /" >> $serverDir/pool.cfg
         fi
-     
+
         echo "user = $userName
 group = www-data
 listen.owner = $userName
@@ -199,19 +215,15 @@ php_admin_flag[log_errors] = on" >> $serverDir/pool.cfg
             echo "Adding PHP dependencies in chroot directory"
             mkdir -p $serverDir/{etc,usr/share,var/lib/php/sessions,tmp}
             cp /etc/localtime $serverDir/etc
-            cp -r /usr/share/zoneinfo $serverDir/usr/share/ 
+            cp -r /usr/share/zoneinfo $serverDir/usr/share/
         fi
-        
+
         # Checking for PHP-FPM include config
         if ! grep -qF "include=$userBasePath/*/*/pool.cfg" /etc/php/*/fpm/php-fpm.conf
         then
             echo "Info: No include for pools in php-fpm config, automatically adding."
             sed -i -e "s/.*include=/;&/" -e "/;include=/a include=$userBasePath/*/*/pool.cfg" /etc/php/*/fpm/php-fpm.conf
         fi
-
-        # Creating default served file
-        echo "   + Moving default page to the user ~/www/ dir"
-        cp index.php $serverDir/www/index.php
 
         # Creating new ftp user
         echo "Adding ftp user '$ftpUser'..."
@@ -223,69 +235,73 @@ php_admin_flag[log_errors] = on" >> $serverDir/pool.cfg
         echo -e "{\n    \"username\": \"$ftpUser\",\n    \"password\": \"$ftpPassword\"\n}" > $serverDir/userpass
 
         # Fixing permissions
-        echo "Gaining access to '$serverDir/' to user '$userName' and group 'www-data' recursively..."
+        echo -e "\nFixing permissions for better security.."
         chmod 750 $serverDir -R
-        echo "   * Fixed permissions to '750'..."
+        echo "   * [$serverDir] Fixed permissions to '750'..."
         chown $userName:www-data $serverDir -R
-        echo "   * Fixed owner to '$userName:www-data'"
+        echo "   * [$serverDir] Fixed owner to '$userName:www-data'"
 
         if [ $sslSecured == 1 ]
         then
-            echo "Disabling access to '$serverDir/{pool.cfg,userpass,.sslCert}' to all user..."
             chmod 005 $serverDir/{pool.cfg,userpass,.sslCert}
-            echo "   * Fixed permissions to '005'..."
+            echo "   * [$serverDir/{pool.cfg,userpass,.sslCert}] Fixed permissions to '005'..."
         else
-            echo "Disabling access to '$serverDir/{pool.cfg,userpass}' to all user..."
             chmod 005 $serverDir/{pool.cfg,userpass}
-            echo "   * Fixed permissions to '005'..."
+            echo "   * [$serverDir/{pool.cfg,userpass}] Fixed permissions to '005'..."
         fi
+
+        # Reloading php-fpm
+        echo -ne "\nReloading php-fpm.."
+        service php*-fpm restart
+        echo "Ok."
         
         # Enabling site
-        echo "Enabling site '$serverName'."
-        a2ensite $serverName > /dev/null
+        $0 resume -s $serverName
     else
-        echo -e "Yes\n"
-        
-        echo "Error: '$serverName' is already configured..."
+        echo "Error: Server already configured..."
         exit 1
     fi
 }
 
 function _removeHost()
 {
-    echo -n "Checking if vhost is existing... "
     if [ -f /etc/apache2/sites-available/$serverName.conf ] && [ -d "$serverDir" ]
     then
-	echo "Ok"
-        
         # Disabling site
-        echo "Disabling site '$serverName'."
-        a2dissite $serverName > /dev/null
-        
+        $0 suspend -s $serverName
+
         # Revoking and removing ssl cert
         if [ -f "$serverDir/.sslCert" ]
         then
             _removeSSL
         fi
 
-        echo -e "\nRemoving user and files..."
+        echo -e "\nRemoving files..."
         # Removing ftp user
         pure-pw userdel $ftpUser -m
         pure-pw mkdb
         service pure-ftpd restart
         echo "   - FTP user '$ftpUser' deleted."
-        
+
         # Removing files
         rm -rf $serverDir
         echo "   - '$serverDir/' dir deleted."
 
         # Deleting apache virtual server
         rm -f /etc/apache2/sites-available/$serverName.conf
-        echo "   - Configuration for '$serverName' removed in apache directory."
-    else
-        echo "Failed"
+        echo "   - Apache configuration for '$serverName' removed."
         
-        echo -e "Error: '$serverName' is not a valid server name..."
+        # Reloading php-fpm
+        echo -ne "\nReloading php-fpm.."
+        service php*-fpm restart
+        echo "Ok."
+        
+        # Reloading apache2
+        echo -n "Reloading apache2.. "
+        service apache2 restart
+        echo "Ok."
+    else
+        echo -e "Error: Server not found."
         exit 1
     fi
 }
@@ -295,20 +311,23 @@ function _addSSL()
     echo -e "\nGenerating SSL Let's Encrypt Certificate..."
     echo "   * Setting up web config for Let's Encrypt activation.."
     echo "<Directory $serverDir/www/>
-    Options -Indexes -FollowSymLinks +MultiViews
-    AllowOverride None
-    Require all granted
+  Options -Indexes -FollowSymLinks +MultiViews
+  AllowOverride None
+  Require all granted
 </Directory>
 <VirtualHost *:80>
-    ServerAdmin $adminEmail
-    DocumentRoot $serverDir/www/
+  ServerAdmin $adminEmail
+  DocumentRoot $serverDir/www/
 
-    ServerName $serverName
-    ServerAlias $serverAlias
+  ServerName $serverName
+  ServerAlias $serverAlias
 </VirtualHost>" > /etc/apache2/sites-available/$serverName.conf
 
-    echo "   * Reloading apache.."
-    service apache2 reload
+    # Reloading apache2
+    echo -n "Reloading apache2.. "
+    service apache2 restart
+    echo "Ok."
+    
     echo "   *** Generating certificate ***"
     if [ ! -z $serverAlias ] # Check if aliases
     then
@@ -333,7 +352,7 @@ function _removeSSL()
     rm -rf $letsEncryptDir/live/$serverName
     rm -rf $letsEncryptDir/archive/$serverName
     rm -f $letsEncryptDir/renewal/$serverName.conf
-    
+
     # Removing file to know we don't an ssl cert
     rm $serverDir/.sslCert
 }
@@ -380,7 +399,7 @@ do
                             exit 1
                         fi
                     ;;
-                     
+
                     # Options
                     --ssl)
                         sslSecured=1
@@ -403,7 +422,7 @@ do
                 echo "Error: No user name specified. Try '$0 add --help'"
                 exit 1
             fi
-            
+
             # Check if username is taken by an user who is not a www user.
             getent passwd $userName >/dev/null 2>&1 && userExists=1
             if [ "$userExists" == 1 ] && [ ! -f $userBasePath/$userName/.wwwUser ]
@@ -412,23 +431,15 @@ do
                 exit 1
             fi
 
-            # Creating vars 
+            # Creating vars
             userDir=$userBasePath/$userName
             serverDir=$userDir/$serverName
             ftpUser=$(echo "$serverName" | tr . -)
             ftpPassword=$(openssl rand -base64 10)
-            
+
             _createHost
 
-            # Applying conf
-            echo "Reloading apache config"
-            service apache2 reload
-
-            echo "Reloading php-fpm config"
-            service php*-fpm restart
-
-            echo "Stored ftp login and password in '$serverDir/userpass'"
-            echo "Done."
+            echo -e "\nStored ftp login and password in '$serverDir/userpass'."
             exit 0
         ;;
         remove)
@@ -467,17 +478,109 @@ do
             # Creating vars
             serverDir=$(find $userBasePath/*/ -maxdepth 1 -name $serverName)
             ftpUser=$(echo "$serverName" | tr . -)
-            
+
             _removeHost
             
-            # Applying conf
-            echo "Reloading apache config"
-            service apache2 reload
+            exit 0
+        ;;
+        suspend)
+            while [ ! -z $1 ]
+            do
+                shift
+                case $1 in
+                    -h | --help)
+                        _helpSuspend
+                    ;;
+                    -s | --server)
+                        shift
+                        if [ ! -z $1 ]
+                        then
+                            if [ -z $serverName ]
+                            then
+                                serverName=$1
+                            else
+                                echo "Error: You can only specify one server name to suspend."
+                                exit 1
+                            fi
+                        else
+                            echo "Error: Please specify a server name after -s|--server argument."
+                            exit 1
+                        fi
+                esac
+            done
 
-            echo "Reloading php-fpm config"
-            service php*-fpm restart
+            # Check if there is a server name
+            if [ -z $serverName ]
+            then
+                echo "Error: No server name specified. Try '$0 remove --help'"
+                exit 1
+            fi
 
-            echo "Done."
+            if [ -f /etc/apache2/sites-available/$serverName.conf ] && [ -f /etc/apache2/sites-enabled/$serverName.conf ]
+            then
+                # So, disable the vhost
+                a2dissite $serverName > /dev/null
+                echo "* Disabled site '$serverName'"
+            else
+                echo "Error: Server not found or already enabled."
+                exit 1
+            fi
+
+            # Reloading apache2
+            echo -n "Reloading apache2.. "
+            service apache2 restart
+            echo "Ok."
+            
+            exit 0
+        ;;
+        resume)
+            while [ ! -z $1 ]
+            do
+                shift
+                case $1 in
+                    -h | --help)
+                        _helpResume
+                    ;;
+                    -s | --server)
+                        shift
+                        if [ ! -z $1 ]
+                        then
+                            if [ -z $serverName ]
+                            then
+                                serverName=$1
+                            else
+                                echo "Error: You can only specify one server name to resume."
+                                exit 1
+                            fi
+                        else
+                            echo "Error: Please specify a server name after -s|--server argument."
+                            exit 1
+                        fi
+                esac
+            done
+
+            # Check if there is a server name
+            if [ -z $serverName ]
+            then
+                echo "Error: No server name specified. Try '$0 remove --help'"
+                exit 1
+            fi
+
+            if [ -f /etc/apache2/sites-available/$serverName.conf ] && [ ! -f /etc/apache2/sites-enabled/$serverName.conf ]
+            then
+                # So, enable the vhost
+                a2ensite $serverName > /dev/null
+                echo "* Enabled site '$serverName'"
+            else
+                echo "Error: Server not found or already enabled."
+                exit 1
+            fi
+
+            # Reloading apache2
+            echo -n "Reloading apache2.. "
+            service apache2 restart
+            echo "Ok."
+            
             exit 0
         ;;
         -h | --help)
